apiVersion: v1
kind: Service
metadata:
  name: kafka
spec:
  type: LoadBalancer
  ports:
    - name: kafka-9092
      port: 9092
      targetPort: 9092
      protocol: TCP 
    - name: kafka-9093
      port: 9093
      targetPort: 9093
      protocol: TCP
  selector:
    app: kafka
  externalIPs:
    - 172.24.33.81
